### ISSUE TITLE
[Bug]: cloud-init fails

### ISSUE THREAD

**Issue by nikolaszimmermann** [kube-hetzner/terraform-hcloud-kube-hetzner#1587]
### Description

```
2024-12-09 09:06:47,387 - subp.py[DEBUG]: Running command ['btrfs', '--version'] with allowed return codes [0] (shell=False, capture=True)
2024-12-09 09:06:47,394 - handlers.py[DEBUG]: finish: init-network/config-resizefs: FAIL: running config-resizefs with frequency always
2024-12-09 09:06:47,394 - util.py[WARNING]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.11/site-packages/cloudinit/config/cc_resizefs.py'>) failed
2024-12-09 09:06:47,394 - util.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.11/site-packages/cloudinit/config/cc_resizefs.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/cloudinit/config/modules.py", line 256, in _run_modules
    ran, _r = cc.run(
              ^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/cloud.py", line 67, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/helpers.py", line 172, in run
    results = functor(**args)
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/config/cc_resizefs.py", line 289, in handle
    resize_cmd = resizer(resize_what, devpth)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/config/cc_resizefs.py", line 79, in _resize_btrfs
    system_btrfs_ver = util.Version.from_str(
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/util.py", line 3185, in from_str
    return cls(*(list(map(int, version.split(".")))))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1\n-EXPERIMENTAL -INJECT -STATIC +LZO +ZSTD +UDEV +FSVERITY +ZONED CRYPTO=builtin'
2024-12-09 09:06:47,396 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.11/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
```

The cloud-init service fails for me, apparently `btrfs --version` returns unparseable output (more than just a version number). The upstream bug is here https://github.com/canonical/cloud-init/issues/5614.

Apparently we use `/usr/bin/cloud-init 23.3-13.1` at the moment.

### Kube.tf file

```terraform
Happens on a default configuration.
```

### Platform

Linux

**Comment by hohmannr** [comment]
Can confirm, we have nearly the same issue. I will investigate a work around.

**Comment by jr-dimedis** [comment]
@nikolaszimmermann 

Do you know of any workaround for this? It sounds like deploying new kube-hetzner nodes with a current MicroOS image is not possible today. Am I right?

The corresponding issue in the SuSE bugzilla is still in status NEW: https://bugzilla.suse.com/show_bug.cgi?id=1229340

**Comment by cvasfi** [comment]
@mysticaltech I spotted a similar error on my /run/cloud-init/result.json:

> {
 "v1": {
  "datasource": "DataSourceHetzner",
  "errors": [
   "('resizefs', ValueError(\"invalid literal for int() with base 10: '12\\\\n-EXPERIMENTAL -INJECT -STATIC +LZO +ZSTD +UDEV +FSVERITY +ZONED CRYPTO=builtin'\"))"
  ]
 }
}

Here's how i initially spotted the issue: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/1451#discussioncomment-12242775

The bugzilla [discussion]( https://bugzilla.suse.com/show_bug.cgi?id=1229340) suggests that the issue is fixed on cloud-init 24.3. The version on my actual server with the issue seems to be "23.3-16.1" though.
